"""
Regenerates reports/day3_analysis.md from the pipeline.

Includes a sensitivity check on the ranking, because a single composite score
is a fragile thing to base a recommendation on: if the top candidate only
wins under one particular weighting, that should be visible rather than
hidden behind a decimal.
"""

from __future__ import annotations

from pathlib import Path

import pandas as pd

from analyze_day3 import (TARGET_PROCESSES, activity_profile, app_surface,
                          build_executions, operator_spread, per_operator,
                          per_process, residual_work, rework, score,
                          systems_per_process, variant_table)
from data_loader import DATASET_B_ROOTS, load_events
from process_context import annotate
from segment import segment

REPO_ROOT = Path(__file__).resolve().parent.parent

# Alternative weightings, to see whether the ordering is an artefact of one
# particular formula.
SCENARIOS = {
    "balanced (default)":    dict(w_vol=0.5, w_time=0.5, use_det=True, use_acc=True, use_branch=True),
    "volume only":           dict(w_vol=1.0, w_time=0.0, use_det=True, use_acc=True, use_branch=True),
    "time only":             dict(w_vol=0.0, w_time=1.0, use_det=True, use_acc=True, use_branch=True),
    "ignore feasibility":    dict(w_vol=0.5, w_time=0.5, use_det=False, use_acc=False, use_branch=False),
    "feasibility-weighted":  dict(w_vol=0.3, w_time=0.3, use_det=True, use_acc=True, use_branch=True),
}


def _score_with(df: pd.DataFrame, w_vol, w_time, use_det, use_acc, use_branch):
    base = w_vol * df.volume + w_time * df.time_share
    if w_vol + w_time:
        base = base / (w_vol + w_time)
    out = base.copy()
    if use_det:
        out = out * df.determinism
    if use_acc:
        out = out * df.data_access
    if use_branch:
        out = out / df.branch_cost
    return out


def sensitivity(ranked: pd.DataFrame) -> pd.DataFrame:
    rows = {}
    for name, kw in SCENARIOS.items():
        s = _score_with(ranked, **kw)
        order = ranked.label_final[s.sort_values(ascending=False).index].tolist()
        rows[name] = {lab: i + 1 for i, lab in enumerate(order)}
    return pd.DataFrame(rows)


def main() -> None:
    ev = annotate(load_events(DATASET_B_ROOTS))
    segs = segment(ev)
    ex = build_executions(ev, segs)
    stats = per_process(ex)
    sysmap = systems_per_process(ev, ex)
    surface = app_surface(ev, ex)
    ranked = score(stats, sysmap, surface)
    variants = variant_table(ex)
    sens = sensitivity(ranked)
    ops = per_operator(ex)
    spread = operator_spread(ex)
    residual = residual_work(ev, ex, TARGET_PROCESSES)
    activity = activity_profile(ev, ex)
    rw = rework(ex)

    real = ranked[ranked.executions >= 5].copy()

    L, A = [], None
    A = L.append
    A("# Day 3 — Step 2: process analysis and automation prioritisation\n")
    A("Generated by `src/report_day3.py`. Curated conclusions and the Step 3 "
      "decision are in [`day3_findings.md`](day3_findings.md).\n")
    A(f"- executions analysed: **{len(ex)}** across "
      f"**{ex.session_id.nunique()}** sessions and "
      f"**{ex.operator.nunique()}** operators")
    A(f"- processes identified: **{len(real)}**")
    split_n = int((ex.label_corrected
                   & (ex.label == "hr_expense_and_payroll_change")).sum())
    fix_n = int(ex.label_corrected.sum()) - split_n
    A(f"- labels changed from the completion comment: "
      f"**{int(ex.label_corrected.sum())}** — of which **{split_n}** are the "
      f"one-screen-two-processes split (a refinement) and **{fix_n}** are "
      f"genuine context mislabels, almost all comments typed outside the "
      f"browser\n")
    A("> All figures are *relative*. The README notes that waiting time was "
      "compressed in the test recording, so absolute seconds are not "
      "meaningful and no annualised savings are extrapolated from them.\n")

    A("## 1. What work is performed, how often, and by how many people\n")
    A("| process | executions | total s | median s | operators | sessions | variants | exception rate |")
    A("|---|---|---|---|---|---|---|---|")
    for r in stats[stats.executions >= 5].itertuples():
        A(f"| `{r.label_final}` | {r.executions} | {r.total_s:.0f} | "
          f"{r.median_s:.1f} | {r.operators} | {r.sessions} | {r.variants} | "
          f"{r.exception_rate:.1%} |")
    A("")

    A("## 2. Handling patterns within each process\n")
    A("The README asks whether the same process is handled differently case "
      "to case. It is, and the completion comment names the pattern "
      "explicitly, so these are read off the data rather than inferred.\n")
    for lab in real.label_final:
        v = variants[variants.label == lab]
        if v.empty:
            continue
        A(f"**`{lab}`** — {len(v)} patterns")
        A("")
        A("| variant | n | median s | exception rate |")
        A("|---|---|---|---|")
        for r in v.itertuples():
            A(f"| {r.variant} | {r.n} | {r.median_s} | {r.exception_rate:.1%} |")
        A("")

    A("## 3. Who does the work\n")
    A("| operator | executions | distinct processes | sessions | total s | median s |")
    A("|---|---|---|---|---|---|")
    for r in ops.itertuples():
        A(f"| `…{r.operator}` | {r.executions} | {r.processes} | {r.sessions} | "
          f"{r.total_s} | {r.median_s} |")
    A("")
    A(f"Four operators, each touching **{ops.processes.min()}–{ops.processes.max()} "
      f"of the {len(real)} processes**. Nobody is a specialist and no process "
      f"is one person's silo, so automating any single process affects all "
      f"four operators rather than displacing one. Median time per execution "
      f"is within {ops.median_s.min()}–{ops.median_s.max()}s across all of "
      f"them, so they work at comparable speed overall.\n")
    A("Where they differ is by process — a wide spread on an identical "
      "procedure suggests it is being applied inconsistently, which is itself "
      "an argument for automating it:\n")
    A("| process | operators | fastest median s | slowest median s | spread |")
    A("|---|---|---|---|---|")
    for r in spread.head(8).itertuples():
        A(f"| `{r.label}` | {r.operators} | {r.fastest_median_s} | "
          f"{r.slowest_median_s} | {r.spread_x}x |")
    A("")

    A("## 4. What an execution is made of\n")
    A("Mean counts inside a single execution. `clipboard` is the one that "
      "matters most: it is a value being carried by hand between fields or "
      "applications, which is exactly the work an integration removes. "
      "Content is redacted throughout, so only the count is available.\n")
    A("| process | median s | clipboard | keystrokes | clicks | app switches | apps |")
    A("|---|---|---|---|---|---|---|")
    for r in activity.itertuples():
        if r.label not in set(real.label_final):
            continue
        A(f"| `{r.label}` | {r.median_s} | {r.clipboard_per_exec} | "
          f"{r.keystrokes_per_exec} | {r.clicks_per_exec} | "
          f"{r.switches_per_exec} | {r.apps_per_exec} |")
    A("")
    A(f"Every process copies and pastes at least once per execution on "
      f"average ({activity.clipboard_total.sum():.0f} clipboard operations "
      f"in total). Manual data movement is universal here, not confined to "
      f"a few awkward flows.\n")

    A("## 4b. Is there rework to eliminate?\n")
    A("\"The tool removes the second pass\" is a standard automation "
      "argument, so it is worth establishing whether a second pass exists. "
      "It matters which identifier is counted:\n")
    A("| reference | identifies | distinct | ref×session pairs | repeated | rate | max |")
    A("|---|---|---|---|---|---|---|")
    for r in rw.itertuples():
        A(f"| `{r.ref_kind}-` | {r.identifies} | {r.distinct_refs} | "
          f"{r.ref_session_pairs} | {r.repeated} | {r.repeat_rate:.1%} | "
          f"{r.max_repeats} |")
    A("")
    A("**Every one of the 64 real invoice cases was worked exactly once.** "
      "The apparent 51% repeat rate on `BATCH-` references is an artefact: "
      "those are *product* codes, only 6 distinct across 78 stock "
      "adjustments, so the same product being adjusted on separate occasions "
      "is not the same case being reworked. Counting all reference kinds "
      "together gives a spurious 18.5% rework rate.\n")
    A("So **there is no rework lever in this data** — the time saved has to "
      "come from making each single pass faster, not from removing a second "
      "one.\n")

    A("## 5. Integration surface\n")
    A("Whether a process can be driven through the portal alone, or also "
      "needs a desktop application. This is the dominant cost difference "
      "between candidates.\n")
    A("| process | browser-only share | desktop apps pulled in |")
    A("|---|---|---|")
    for r in surface.itertuples():
        if r.label_final not in set(real.label_final):
            continue
        A(f"| `{r.label_final}` | {r.browser_only_share:.1%} | "
          f"{r.desktop_apps or '—'} |")
    A("")
    A(f"Median distinct portals touched within a single execution: "
      f"**{pd.Series(sysmap).median():.1f}** for every process. A case stays "
      f"inside one system; it is the desktop applications, not cross-system "
      f"navigation, that drive integration cost.\n")

    A("## 6. Ranked automation candidates\n")
    A("```\n"
      "opportunity = (volume + time_share)/2 x determinism x data_access\n"
      "              ----------------------------------------------------\n"
      "                                branch_cost\n"
      "```\n")
    A("| # | process | executions | total s | determinism | exceptions | browser-only | variants | **opportunity** |")
    A("|---|---|---|---|---|---|---|---|---|")
    for i, r in enumerate(real.itertuples(), 1):
        A(f"| {i} | `{r.label_final}` | {r.executions} | {r.total_s:.0f} | "
          f"{r.determinism:.3f} | {r.exception_nature} | {r.data_access:.3f} | "
          f"{r.variants} | **{r.opportunity:.3f}** |")
    A("")
    A("`exceptions` distinguishes an exception that is a labelled property of "
      "the case (`predictable` — one branch to implement) from one discovered "
      "during the work and unpredictable from anything the log captures "
      "(`judgement` — work a machine cannot take over). Only the latter "
      "reduces `determinism`. See the module docstring in "
      "`src/analyze_day3.py` for the measurements behind each assignment.\n")

    A("## 6b. What would remain manual, for the chosen scope\n")
    A("Observed time for the three target processes, split into the part "
      "spent in the portal and the part that pulls in Word, Excel or "
      "Notepad. The tool addresses the former; the latter is untouched in "
      "this phase. Review time is retained in full on top of this, because "
      "the tool prepares and a human commits.\n")
    A("| process | executions | total s | portal-only s | desktop-involved s | addressable |")
    A("|---|---|---|---|---|---|")
    for r in residual.itertuples():
        A(f"| `{r.label}` | {r.executions} | {r.total_s} | {r.portal_only_s} | "
          f"{r.desktop_involved_s} | {r.addressable_share:.1%} |")
    tot = residual.total_s.sum()
    add = residual.portal_only_s.sum()
    A("")
    A(f"**{add:.0f}s of {tot:.0f}s ({100 * add / tot:.1f}%)** of the targeted "
      f"work is portal-only and therefore addressable. The remaining "
      f"{tot - add:.0f}s involves a desktop application and stays manual.\n")

    A("## 7. Sensitivity of the ranking\n")
    A("Rank of each process under alternative weightings. A recommendation "
      "that only survives one formula is not a recommendation.\n")
    keep = [l for l in real.label_final]
    s = sens.loc[[l for l in keep if l in sens.index]]
    A("| process | " + " | ".join(s.columns) + " |")
    A("|---" * (len(s.columns) + 1) + "|")
    for lab, row in s.iterrows():
        A(f"| `{lab}` | " + " | ".join(str(int(v)) for v in row) + " |")
    A("")

    out = REPO_ROOT / "reports/day3_analysis.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO_ROOT)} ({len(L)} lines)")
    print("\n=== sensitivity (rank per scenario) ===")
    print(s.to_string())


if __name__ == "__main__":
    main()
