"""
Regenerates reports/day2_segmentation.md from the pipeline, so every number
in the report is reproducible rather than transcribed by hand.

    python src/report_day2.py
"""

from __future__ import annotations

import re
from collections import Counter, defaultdict
from pathlib import Path

import pandas as pd

from data_loader import DATASET_B_ROOTS, load_events
from evaluate import (check_boundary_alignment, check_label_stability,
                      check_pcode_purity, check_tiling)
from executions import completion_markers
from process_context import PROCESS_LABELS, annotate
from segment import MIN_DURATION_S, MIN_SUBSTANTIVE, segment

REPO_ROOT = Path(__file__).resolve().parent.parent
JP = re.compile(r"[぀-ヿ一-鿿]")


def _dig(d, *keys):
    cur = d
    for k in keys:
        if not isinstance(cur, dict):
            return None
        cur = cur.get(k)
    return cur


def vocabulary(ev: pd.DataFrame, top: int = 6) -> dict[str, list[tuple[str, int]]]:
    """Japanese business vocabulary observed per process label, from clicked
    element names and typed field values. This is the evidence each label is
    named from."""
    vocab: dict[str, Counter] = defaultdict(Counter)
    for r in ev.to_dict("records"):
        lab = r.get("process_label")
        if not isinstance(lab, str):
            continue
        p = r.get("payload") or {}
        for path in (("target_element", "name"), ("target_element", "value"),
                     ("target_field", "value"), ("element", "text")):
            v = _dig(p, *path)
            if isinstance(v, str) and JP.search(v) and 2 < len(v) < 60:
                vocab[lab][v.strip()[:52]] += 1
    return {k: v.most_common(top) for k, v in vocab.items()}


def app_mix(ev: pd.DataFrame, top: int = 4) -> dict[str, list[tuple[str, int]]]:
    out = {}
    for lab, g in ev[ev.process_label.notna()].groupby("process_label"):
        out[lab] = g.app_name.value_counts().head(top).items()
    return {k: list(v) for k, v in out.items()}


def main() -> None:
    ev = annotate(load_events(DATASET_B_ROOTS))
    episodes = segment(ev, split_executions=False)
    segs = segment(ev)
    markers = completion_markers(ev)
    ep_align = check_boundary_alignment(episodes, ev)

    tiling = check_tiling(segs, ev)
    purity = check_pcode_purity(segs, ev)
    align = check_boundary_alignment(segs, ev)
    stability = check_label_stability(ev)
    vocab = vocabulary(ev)
    apps = app_mix(ev)

    per_label = segs.groupby("label").agg(
        n_segments=("label", "size"),
        median_s=("duration_s", "median"),
        total_s=("duration_s", "sum"),
        n_sessions=("session_id", "nunique"),
    ).round(1).sort_values("total_s", ascending=False)

    out = REPO_ROOT / "reports/day2_segmentation.md"
    out.parent.mkdir(parents=True, exist_ok=True)
    L = []
    A = L.append

    A("# Day 2 — Step 1 segmentation results\n")
    A("Generated by `src/report_day2.py`. Curated interpretation lives in "
      "[`day2_findings.md`](day2_findings.md).\n")
    A(f"- events: **{len(ev):,}** across **{ev.session_id.nunique()}** dataset B sessions")
    A(f"- process episodes: **{len(episodes)}**")
    A(f"- **case executions emitted: {len(segs)}** "
      f"({len(segs) / len(episodes):.1f} per episode) — this is the deliverable")
    A(f"- completion markers found: **{len(markers)}**")
    A(f"- distinct labels: **{segs.label.nunique()}**")
    A(f"- thresholds: `MIN_SUBSTANTIVE={MIN_SUBSTANTIVE}`, "
      f"`MIN_DURATION_S={MIN_DURATION_S}`\n")
    A("Two granularities exist and both are reported below. An *episode* is a "
      "contiguous stretch of work in one process context; an *execution* is a "
      "single case within it, bounded by the completion comment the worker "
      "writes. The README asks for individual executions, so those are what "
      "`segments.jsonl` contains.\n")

    A("## 1. Segments per process\n")
    A("| label | executions | sessions | median s | total s |")
    A("|---|---|---|---|---|")
    for lab, r in per_label.iterrows():
        A(f"| `{lab}` | {int(r.n_segments)} | {int(r.n_sessions)} | "
          f"{r.median_s} | {r.total_s} |")
    A("")

    A("## 2. Validation without ground truth\n")
    A("Dataset A's `gt.jsonl` never arrived, so these are internal checks. "
      "Each can fail, which is what makes them worth running — and check 4 "
      "did fail on its first version.\n")

    A("### 2.1 Tiling: no overlap, near-complete coverage\n")
    A(f"- total overlap across all sessions: **{tiling.overlap_s.sum():.3f}s**")
    A(f"- mean wall-clock coverage: **{tiling.coverage_pct.mean():.1f}%** "
      f"(min {tiling.coverage_pct.min():.1f}%, max {tiling.coverage_pct.max():.1f}%)\n")
    A("| session | segments | wall s | covered s | coverage | overlap s |")
    A("|---|---|---|---|---|---|")
    for r in tiling.itertuples():
        A(f"| `{r.session_id[4:22]}` | {r.n_segments} | {r.wall_s} | "
          f"{r.covered_s} | {r.coverage_pct}% | {r.overlap_s} |")
    A("")

    A("### 2.2 Independent `p_code` agreement\n")
    A("The portal stamps a process code `P<n>` into clicked UIA row names, "
      "produced independently of the URL the label is derived from.\n")
    A(f"- segments with `p_code` evidence: **{purity['segments_with_pcode']}** "
      f"of {len(segs)} (+{purity['segments_unresolved_excluded']} excluded as `*_unresolved`)")
    A(f"- label agrees with `p_code`: **{purity['segments_pure']} "
      f"({purity['purity_pct']}%)**\n")
    if purity["mismatches"]:
        A(f"The {len(purity['mismatches'])} disagreement(s):\n")
        A("| session | label | expected | observed | duration s |")
        A("|---|---|---|---|---|")
        for m in purity["mismatches"]:
            A(f"| `{m['session_id'][4:22]}` | `{m['label']}` | "
              f"`{m['expected']}` | {m['observed']} | {m['duration_s']} |")
        A("")

    A("### 2.3 Boundary alignment\n")
    A(f"- **episode** boundaries (process switches): "
      f"**{ep_align['aligned']} / {ep_align['boundaries']} "
      f"({ep_align['aligned_pct']}%)** within {ep_align['window_s']}s of a "
      f"`browser_navigation` or `app_switch`")
    A(f"- **execution** boundaries (individual cases): "
      f"**{align['aligned']} / {align['boundaries']} "
      f"({align['aligned_pct']}%)**\n")
    A("> Caveat, stated because it matters: the episode figure is close to "
      "tautological. Episodes are cut where the process context changes, and "
      "the context changes *because* of navigation events, so a high score "
      "confirms the implementation does what it intends — not that the "
      "boundaries are the ones a human would draw. It is a regression guard, "
      "not accuracy.\n")
    A("> The execution figure is *expected* to be much lower, and that is the "
      "point: most case boundaries happen inside one screen, with no "
      "navigation to align with. A high number there would mean the "
      "executions were not being split at all.\n")

    A("### 2.4 Label stability\n")
    A("The deliverable requires the same process to always receive the same "
      "label. Every resolvable label maps to exactly one (system, route) "
      "pair:\n")
    A("| label | events | distinct pairs | pair | dominant |")
    A("|---|---|---|---|---|")
    for r in stability.itertuples():
        A(f"| `{r.label}` | {r.n_events} | {r.n_distinct_pairs} | "
          f"`{r.dominant_pair}` | {r.dominant_pct}% |")
    A("")

    A("## 3. The process taxonomy and the evidence for each name\n")
    A("Labels are named from the business vocabulary on each screen, not from "
      "the route string — the route names are actively misleading (see "
      "`day2_findings.md`).\n")
    port_sys = {"5132": "HR人事給与システム", "5133": "財務会計システム",
                "5134": "受発注在庫管理システム"}
    inv = {v: k for k, v in PROCESS_LABELS.items()}
    for lab in per_label.index:
        pr = inv.get(lab)
        A(f"### `{lab}`\n")
        if pr:
            A(f"`{port_sys[pr[0]]}` ({pr[0]}) &middot; `{pr[1]}`\n")
        A(f"- apps: " + ", ".join(f"{a} ({n})" for a, n in apps.get(lab, [])))
        if vocab.get(lab):
            A("- observed vocabulary:")
            for t, c in vocab[lab]:
                A(f"    - `{t}` ×{c}")
        A("")

    out.write_text("\n".join(L), encoding="utf-8")
    print(f"wrote {out.relative_to(REPO_ROOT)} ({len(L)} lines)")


if __name__ == "__main__":
    main()
